# Single source of truth: each entry generates BOTH the .theme-dark declaration
# and the @settings control, so they cannot drift apart.

FONTS = ["Inter","Bricolage Grotesque","Roboto","Montserrat","system-ui","Arial","Helvetica",
         "Verdana","Tahoma","Trebuchet MS","Segoe UI","Georgia","Times New Roman","Garamond",
         "Palatino","Merriweather","Lato","Open Sans","Noto Sans","Nunito","Poppins","Raleway",
         "Rubik","Work Sans","IBM Plex Sans","Ubuntu"]
MONO = ["ui-monospace","Consolas","Courier New","Cascadia Code","JetBrains Mono","Fira Code",
        "Source Code Pro","IBM Plex Mono","Roboto Mono","Menlo","Monaco","Ubuntu Mono"]

# kind: H=heading, CT=class-toggle, C=color, RGBA=color w/ opacity, T=text, S=select,
#       N=number slider, RAW=declared but not exposed
S = [
 ("H","features","Features",2,None),
 ("CT","pure-amoled-background","Pure AMOLED Background",
  "Force true black (#000000) everywhere. Overrides Base Dark below."),
 ("CTON","style-tables","Style Tables",
  "Turn off to fall back to Obsidian's own table appearance."),
 ("CTON","style-callouts","Style Callouts",
  "Turn off to restore Obsidian's callout padding, radius, border and background tint. Callout colours still follow the accent palette, because Obsidian derives them from it."),
 ("CTON","style-canvas","Style Canvas",
  "Turn off to restore Obsidian's canvas background, dot grid and card labels."),
 ("CTON","style-graph","Style Graph View",
  "Turn off to restore Obsidian's graph view colours."),
 ("CT","custom-background","Custom Background Image",
  "Show an image behind the workspace. Turn this on, then set the URL below."),
 ("T","custom-bg-image","none","Background Image URL",
  'Example: url("app://local/C:/Users/you/Pictures/bg.jpg"). Keep the url(\"...\") wrapper. Use "none" to disable.'),
 ("N","custom-bg-opacity",0.25,0,1,0.05,"Background Image Opacity",
  "Lower keeps text readable. This is an AMOLED theme; anything above ~0.4 costs you the black."),
 ("N","custom-bg-blur",0,0,40,1,"Background Image Blur",
  "Blur radius in pixels."),
 ("S","custom-bg-size","cover",["cover","contain","auto","100% 100%"],"Background Image Size",None),
 ("S","custom-bg-position","center",["center","top","bottom","left","right"],"Background Image Position",None),

 ("H","typography","Typography",2,None),
 ("S","header-font","Inter",FONTS,"Header Font",
  "Inter ships with Obsidian. Bricolage Grotesque, Roboto and Montserrat are embedded in this theme. The rest only work if installed on your system."),
 ("T","header-font-custom","","Custom Header Font",
  "Any font family installed on your system. Overrides the dropdown above when set. Leave empty to use the dropdown."),
 ("S","body-font","Inter",FONTS,"Body Font",
  "Roboto and Montserrat are Latin-1 subsets and fall back for accented characters."),
 ("T","body-font-custom","","Custom Body Font",
  "Overrides the dropdown above when set. Leave empty to use the dropdown."),
 ("S","monospace-font","ui-monospace",MONO,"Monospace Font","Code blocks and inline code."),
 ("T","monospace-font-custom","","Custom Monospace Font",
  "Overrides the dropdown above when set. Leave empty to use the dropdown."),
 ("T","font-text-size","16px","Editor Font Size",None),
 ("T","file-line-width","700px","Editor Line Width",None),

 ("H","heading-sizes","Heading Sizes",3,None),
 ("T","h1-size","2.2em","H1 Font Size",None),
 ("T","h2-size","1.8em","H2 Font Size",None),
 ("T","h3-size","1.5em","H3 Font Size",None),
 ("T","h4-size","1.3em","H4 Font Size",None),
 ("T","h5-size","1.1em","H5 Font Size",None),
 ("T","h6-size","1em","H6 Font Size",None),

 ("H","heading-colors","Heading Colors",3,None),
 ("C","h1-color","var(--red)","H1 Color",None),
 ("C","h2-color","var(--yellow)","H2 Color",None),
 ("C","h3-color","var(--green)","H3 Color",None),
 ("C","h4-color","var(--purple)","H4 Color",None),
 ("C","h5-color","var(--frost0)","H5 Color",None),
 ("C","h6-color","var(--frost2)","H6 Color",None),

 ("H","inline-title-sec","Note Title",3,None),
 ("C","inline-title-color","var(--text-primary)","Inline Title Color",None),
 ("T","inline-title-size","2.2em","Inline Title Size",None),
 ("T","inline-title-weight","700","Inline Title Weight",None),

 ("H","accent-colors","Accent Colors",2,None),
 ("C","primary-accent","var(--frost0)","Primary Accent",
  "Links, active states and interactive highlights."),
 ("C","secondary-accent","var(--frost2)","Secondary Accent","Hover state for the above."),
 ("CX","red","#bf616a","Red",
  "Also writes --red-rgb, which feeds Obsidian's own colour palette and so drives callouts and canvas colours."),
 ("CX","orange","#d08770","Orange",
  "Also writes --orange-rgb, which feeds Obsidian's own colour palette and so drives callouts and canvas colours."),
 ("CX","yellow","#ebcb8b","Yellow",
  "Also writes --yellow-rgb, which feeds Obsidian's own colour palette and so drives callouts and canvas colours."),
 ("CX","green","#a3be8c","Green",
  "Also writes --green-rgb, which feeds Obsidian's own colour palette and so drives callouts and canvas colours."),
 ("CX","purple","#b48ead","Purple",
  "Also writes --purple-rgb, which feeds Obsidian's own colour palette and so drives callouts and canvas colours."),
 ("CX","frost0","#8fbcbb","Cyan Frost",
  "Also writes --frost0-rgb, which feeds Obsidian's own colour palette and so drives callouts and canvas colours."),
 ("CX","frost2","#81a1c1","Blue Frost",
  "Also writes --frost2-rgb, which feeds Obsidian's own colour palette and so drives callouts and canvas colours."),

 ("H","base-colors","Base Colors",2,
  "The greyscale ramp. Base Dark is the page background; the rest step up toward white."),
 ("C","color-base-00","#0e0e0e","Base Dark (background)",None),
 ("C","color-base-05","#343434","Darker Secondary",None),
 ("C","color-base-10","#242424","Slightly Lighter Dark",None),
 ("C","color-base-20","#1a1a1a","Even Lighter Dark",None),
 ("C","color-base-25","#262626","Soft Highlight",None),
 ("C","color-base-30","#333333","Dark Gray",None),
 ("C","color-base-35","#363636","Medium Dark",None),
 ("C","color-base-40","#4a4a4a","Mid-Tone Gray",None),
 ("C","color-base-50","#666666","Light Gray",None),
 ("C","color-base-60","#999999","Lighter Gray",None),
 ("C","color-base-70","#bbbbbb","Almost White Gray",None),
 ("C","color-base-80","#dddddd","Very Light Gray",None),
 ("C","color-base-90","#eeeeee","Almost White",None),
 ("C","color-base-100","#ffffff","Pure White",None),

 ("H","text-colors","Text Colors",2,
  "Raise these if you are on a panel with a contrast ratio below about 3000:1, where the darker greys stop separating from the background."),
 ("C","text-primary","var(--color-base-80)","Primary Text",None),
 ("C","text-secondary","var(--color-base-60)","Secondary Text","Muted text: metadata, inactive tabs, sidebar detail."),
 ("C","text-tertiary","var(--color-base-50)","Faint Text","Line numbers and the dimmest UI text."),
 ("C","text-error","var(--red)","Error Text",None),
 ("C","text-warning","var(--yellow)","Warning Text",None),
 ("C","bold-color","var(--color-base-100)","Bold Text",None),
 ("C","italic-color","var(--frost0)","Italic Text",None),
 ("RGBA","text-highlight-bg","rgba(235, 203, 139, 0.35)","Highlight Background",None),

 ("H","sidebar","Sidebar and Navigation",2,
  "The file explorer, outline and tab headers. Raise these if the sidebar reads too dark."),
 ("C","nav-item-color","var(--color-base-70)","Sidebar Text",None),
 ("C","nav-item-color-hover","var(--color-base-90)","Sidebar Text (hover)",None),
 ("C","nav-item-color-active","var(--color-base-100)","Sidebar Text (active)",None),
 ("C","nav-item-background-hover","var(--color-base-20)","Sidebar Background (hover)",None),
 ("C","nav-item-background-active","var(--color-base-25)","Sidebar Background (active)",None),
 ("T","nav-item-size","14px","Sidebar Font Size",None),
 ("T","nav-item-weight","400","Sidebar Font Weight",None),
 ("C","nav-indentation-guide-color","var(--color-base-30)","Indentation Guide",None),
 ("C","icon-color","var(--color-base-70)","Icon Color",None),
 ("C","icon-color-hover","var(--color-base-90)","Icon Color (hover)",None),
 ("C","icon-color-active","var(--primary-accent)","Icon Color (active)",None),
 ("C","tab-text-color","var(--color-base-60)","Tab Text",None),
 ("C","tab-text-color-active","var(--color-base-90)","Tab Text (active)",None),
 ("C","titlebar-text-color","var(--text-primary)","Titlebar Text",None),
 ("C","divider-color","var(--color-base-20)","Pane Divider",None),

 ("H","buttons","Buttons",2,None),
 ("C","button-background","var(--background-primary)","Button Background",None),
 ("C","button-text","var(--color-base-80)","Button Text",None),
 ("C","button-border","var(--background-primary)","Button Border",None),

 ("H","selection-focus","Selection and Focus",2,None),
 ("C","focus-border","var(--purple)","Focus Border",None),
 ("RGBA","selection-background","rgba(163, 190, 140, 0.35)","Selection Background",
  "Background behind selected text."),

 ("H","markdown","Markdown Elements",2,None),
 ("C","blockquote-color","var(--text-secondary)","Blockquote Text",None),
 ("C","blockquote-border-color","var(--purple)","Blockquote Border",None),
 ("T","blockquote-border-thickness","3px","Blockquote Border Thickness",None),
 ("C","hr-color","var(--color-base-30)","Horizontal Rule",None),
 ("T","hr-thickness","2px","Horizontal Rule Thickness",None),
 ("C","list-marker-color","var(--color-base-60)","List Bullet",None),
 ("C","tag-color","var(--frost0)","Tag Text",None),
 ("RGBA","tag-background","rgba(143, 188, 187, 0.15)","Tag Background",None),
 ("C","checkbox-color","var(--primary-accent)","Checkbox Fill",None),
 ("C","checkbox-marker-color","var(--color-base-00)","Checkbox Tick",None),
 ("C","checkbox-border-color","var(--color-base-40)","Checkbox Border",None),

 ("H","tables","Tables",2,None),
 ("CTON","table-header-styling","Header Styling",
  "Give the header row its own background and hover colour."),
 ("CTON","table-zebra-striping","Zebra Striping",
  "Tint alternating rows."),
 ("CT","table-column-striping","Column Striping",
  "Tint alternating columns. Off by default: Obsidian paints column stripes on the cell and row stripes on the row, and the cell wins, so having both on gives you a checkerboard instead of columns."),
 ("RGBA","table-background","rgba(0, 0, 0, 0)","Table Background",None),
 ("C","table-header-background","var(--color-base-35)","Header Background",
  "Sits clearly above both the page background and the row stripe (1.60:1 and 1.44:1). The old value was only 1.12:1 against the stripe, which read as the same shade."),
 ("C","table-header-background-hover","var(--color-base-40)","Header Background (hover)",
  "Must be lighter than the header background, not darker."),
 ("C","table-header-color","var(--text-primary)","Header Text",None),
 ("T","table-header-weight","600","Header Weight",None),
 ("T","table-header-size","0.9em","Header Size",None),
 ("C","table-text-color","var(--text-primary)","Cell Text",None),
 ("T","table-text-size","0.95em","Cell Text Size",None),
 ("T","table-line-height","1.5","Line Height",None),
 ("C","table-row-alt-background","var(--color-base-20)","Alternating Row",
  "Zebra striping. Kept subtle (1.11:1 against the background) because a strong stripe on an AMOLED panel is a row of lit pixels."),
 ("C","table-row-background-hover","var(--color-base-25)","Row (hover)",
  "Deliberately the same as the alternating-row hover, so the highlight reads the same whether or not the row is striped."),
 ("C","table-row-alt-background-hover","var(--color-base-25)","Alternating Row (hover)",None),
 ("C","table-column-alt-color","var(--color-base-10)","Alternating Column Colour",
  "Only applies when Column Striping is on."),
 ("C","table-border-color","var(--color-base-20)","Border",None),
 ("T","table-border-width","1px","Border Width",None),
 ("T","table-header-border-width","2px","Header Border Width",None),
 ("C","table-header-border-color","var(--color-base-40)","Header Border",
  "Border colour for the header cells. Note that Header Border Width sets the border on TOP of the header row, not under it."),
 ("T","table-column-max-width","none","Column Max Width",None),
 ("S","table-white-space","normal",["normal","nowrap","pre-wrap"],"Cell Wrapping",None),
 ("S","table-cell-vertical-alignment","top",["top","middle","bottom"],"Cell Alignment",None),
 ("RGBA","table-selection","rgba(143, 188, 187, 0.10)","Selection",None),
 ("C","table-selection-border-color","var(--primary-accent)","Selection Border",None),

 ("H","code","Code",2,None),
 ("C","code-background","var(--background-primary)","Code Background",None),
 ("C","code-normal","var(--color-base-80)","Default",None),
 ("C","code-comment","var(--color-base-50)","Comment",None),
 ("C","code-function","var(--yellow)","Function",None),
 ("C","code-important","var(--orange)","Important",None),
 ("C","code-keyword","var(--purple)","Keyword",None),
 ("C","code-property","var(--frost0)","Property",None),
 ("C","code-punctuation","var(--color-base-60)","Punctuation",None),
 ("C","code-string","var(--green)","String",None),
 ("C","code-tag","var(--red)","Tag",None),
 ("C","code-value","var(--purple)","Value",None),

 ("H","callouts","Callouts",2,None),
 ("T","callout-radius","8px","Corner Radius",None),
 ("T","callout-padding","12px 16px","Padding",None),
 ("T","callout-border-width","1px","Border Width",None),
 ("N","callout-border-opacity",0.25,0,1,0.05,"Border Opacity",None),
 ("N","callout-bg-opacity",0.08,0,0.4,0.01,"Background Opacity",
  "How strongly a callout tints its background. Obsidian hardcodes 0.10; this theme ships 0.08, because a lit background is what an AMOLED theme is trying to avoid."),
 ("T","callout-title-weight","600","Title Weight",None),
 ("T","callout-title-padding","0","Title Padding",None),
 ("T","callout-content-padding","0","Content Padding",None),
 ("S","callout-blend-mode","normal",["normal","multiply","screen","lighten","darken"],"Blend Mode",None),

    ("H","canvas","Canvas",2,
  "Canvas node colours follow the accent palette above, because Obsidian derives them from it."),
 ("C","canvas-background","var(--background-primary)","Canvas Background",None),
 ("C","canvas-dot-pattern","var(--color-base-20)","Dot Grid",None),
 ("C","canvas-card-label-color","var(--text-tertiary)","Card Label",None),
 ("T","canvas-controls-radius","8px","Controls Radius",None),

 ("H","graph","Graph View",2,None),
 ("C","graph-line","var(--color-base-30)","Link Line",None),
 ("C","graph-node","var(--color-base-70)","Node",None),
 ("C","graph-node-focused","var(--primary-accent)","Node (focused)",None),
 ("C","graph-node-tag","var(--yellow)","Tag Node",None),
 ("C","graph-node-attachment","var(--purple)","Attachment Node",None),
 ("C","graph-node-unresolved","var(--color-base-40)","Unresolved Node",None),
 ("C","graph-text","var(--text-primary)","Node Label",None),

 ("H","scrollbar","Scrollbar",2,None),
 ("RGBA","scrollbar-bg","rgba(0, 0, 0, 0)","Track",None),
 ("C","scrollbar-thumb-bg","var(--color-base-30)","Thumb",None),
 ("C","scrollbar-active-thumb-bg","var(--color-base-40)","Thumb (active)",None),

 ("H","corners","Corners",2,None),
 ("T","radius-s","4px","Small Radius",None),
 ("T","radius-m","6px","Medium Radius",None),
 ("T","radius-l","10px","Large Radius",None),

 ("H","status-bar-sec","Status Bar",2,None),
 ("C","status-bar-background","var(--color-base-05)","Status Bar Background",None),
 ("C","status-bar-foreground","var(--color-base-100)","Status Bar Foreground",None),
]
